pages/orders/urls.py
from django.urls import path
from django.urls import path
from orders.views import OrdersPageView, charge,OrdersViajePageView,OrdersHospPageView

urlpatterns=[
    path('charge/', charge, name='charge'),
    path('orders/purchase/<int:pk>',OrdersPageView.as_view(), name='orders'),
    path('orders_viaje/purchase/<int:pk>',OrdersViajePageView.as_view(), name='orders_viaje'),
    path('orders_hosp/purchase/<int:pk>',OrdersHospPageView.as_view(), name='orders_hosp'),
    
]

pages/proyecto1/urls.py
from django.urls import path,include
from django.contrib import admin
from mipagina.views import HomePageView,RegistrarView,VueloPageView,HospedajePageView,DescripViajesPageView,DescripVuelosPageView,DescripHospPageView,ViajeDeleteView,AboutPageView
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from orders.views import OrdersPageView, charge
#rutas para los templates 
urlpatterns = [
    path('admin/', admin.site.urls),
     path('accounts/', include('allauth.urls')),
    path('mipagina/', include('mipagina.urls')),
    path('orders/', include('orders.urls')),
    path('charge/', charge, name='charge'),
    path('orders/purchase',OrdersPageView.as_view(), name='orders'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('Home',HomePageView.as_view(), name='home'),
    path('', TemplateView.as_view(template_name='vuelo.html'), name='vuelo'),
    path('vuelo',VueloPageView.as_view(), name='vuelo'),
    path('', TemplateView.as_view(template_name='hospedaje.html'), name='hospedaje'),
    path('hospedaje',HospedajePageView.as_view(), name='hospedaje'),
    path('Acerca_de', TemplateView.as_view(template_name='About.html'), name='About'),
    path('Acerca_de',AboutPageView.as_view(), name='About'),
    path('registrar/', RegistrarView.as_view(),name='registrar'),
    path('Descripcion/Viajes/<int:pk>',DescripViajesPageView.as_view(),name='DescViajes'),
    path('Descripcion/Vuelos/<int:pk>',DescripVuelosPageView.as_view(),name='DescVuelos'),
    path('Descripcion/Hospedajes/<int:pk>',DescripHospPageView.as_view(),name='DescHosp'),
    path('Viaje/<int:pk>/delete',ViajeDeleteView.as_view(),name='deleteViaje'),
    path('oauth/', include('social_django.urls', namespace='social')), 
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/mipagina/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth import get_user_model



# Create your models here.

#modelo del usario personalizado del proyecto final
class UsuarioPers(AbstractUser):
    edad = models.PositiveIntegerField(null=True, blank=True)
    telefono = models.PositiveIntegerField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    genero = models.CharField(null=True,blank=True, max_length=1)
    
    

#se presntan los diferentes modelos de la base de datos diseñada en posgres 
#modelo de las ciudades 
class Ciudad(models.Model):
    nombre = models.TextField(default="")
    
    def __str__(self):
        return self.nombre

#modelo de hospedaje en la base de datos 
class Hospedaje(models.Model):
    ciudad = models.ForeignKey(
        Ciudad,
        default="",
        on_delete= models.CASCADE,
        related_name="ciudad",
    )
    beneficios = models.TextField(default="")
    presio = models.TextField(default="")
    img =models.ImageField(null=True, blank=True, upload_to="images/")
  
    class Meta:
        permissions = [
            ('add_access','Permite agregar registros'),
        ]

    def __str__(self):
        return self.ciudad

    def get_absolute_url(self):
        return reverse('HopsedajeDetalle', args=[str(self.id)])

#modelo de vuelo en la base de datos 
class Vuelo(models.Model):
    ciudad = models.ForeignKey(
        Ciudad,
        default="",
        on_delete= models.CASCADE,
        related_name="ciudadVue",
    )
    descrpicion = models.TextField(default="")
    escala = models.TextField(default="")
    presio = models.TextField(default="")
    img = models.ImageField(null=True, blank=True, upload_to="images/")
    
    class Meta:
        permissions = [
            ('usuariocomun','Permite a los usarios agregar,editar,eliminar'),
        ]
    
    def __str__(self):
        return self.ciudad

    def get_absolute_url(self):
        return reverse('', args=[str(self.id)])

#modelo de viaje en la base de datos 
class Viaje(models.Model):
    ciudad = models.ForeignKey(
        Ciudad,
        default="",
        on_delete= models.CASCADE,
        related_name="ciudadV",
    )
    descrpicion = models.TextField(default="")
    presio = models.TextField(default="")
    img = models.ImageField(null=True, blank=True, upload_to="images/")
    noches = models.TextField(default="")

    class Meta:
            permissions = [
                ('usuarioPerTot','Permite a los usarios agregar,editar,eliminar en modelo viaje'),
            ]
    def __str__(self):
        return self.ciudad

    def get_absolute_url(self):
        return reverse('', args=[str(self.id)])


#modelo de los comentarios  agregando dos llaves foraneas para los autores y los usarios
class ComentarioVuelo(models.Model):
    comentario = models.TextField(default="")
    Vuelo = models.ForeignKey(
        Vuelo,
        default="",
        on_delete= models.CASCADE,
        related_name="comentariosVuelo",
    )
        
    def __str__(self):
        return self.comentario
    
class ComentarioViaje(models.Model):
    comentario = models.TextField(default="")
    Viaje = models.ForeignKey(
        Viaje,
        default="",
        on_delete= models.CASCADE,
        related_name="comentariosViaje",
    )
        
    def __str__(self):
        return self.comentario
    

class ComentarioHosp(models.Model):
    comentario = models.TextField(default="")
    Hospedaje = models.ForeignKey(
        Hospedaje,
        default="",
        on_delete= models.CASCADE,
        related_name="comentariosHosp",
    )

    def __str__(self):
        return self.comentario
    
    def get_absolute_url(self):
        return reverse('', args=[str(self.id)])

pages/templates/About.html
<!--Agregar el archivo base -->
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!--creacion del archivo de acerca de de la empresa que contendra la informacion de la empresa ademas de
un boton que te direccionara a la pagina del tecnologico  -->
<div id="up_tit"><h3>Acerca de Go Travel</h3></div>

<div id="contabout1">
          
            <div id="contenedor_1">
                <h3 style="text-align: center;">Conoce mas acerca de nuestra Mision</h3>
                <button id="btnjs1" class="btn btn-success">Ver mas ...</button>
            </div>
</div> 


<div style="background-color: royalblue;width: 1370px;height: 200px;">
</div>

<div id="contabout2">
       
        <div id="contenedor_2">
            <h3 style="text-align: center;">Conoce mas acerca de nuestra Vision</h3>
            <button id="btnjs2" class="btn btn-success">Ver mas ...</button>
        </div>
</div> 






<div style="background-color: rgb(1, 71, 22);width: 1370px;height: 200px;">
</div>
<div id="contabout3">
       
        <div style="height: 60%;">
           
            <div id="contenedor_3">
                <h3 style="text-align: center;">Conoce mas acerca de nuestros Objetivos</h3>
                <button id="btnjs3" class="btn btn-success">Ver mas ...</button>
            </div>
           
</div> 


<script>
    $(document).ready(function(){
      $("#btnjs1").click(function(){
        Swal.fire(
        'Mision',
        'nuestra mision es ser la mejor empresa de transporte del pais ademas de ser una de las empresas mas grandes que exista',
        'success'
        )
    })
  })
</script>

<script>
    $(document).ready(function(){
      $("#btnjs2").click(function(){
        Swal.fire(
        'Vision',
        'ser una de las 5 empresas principales de viaje en el mundo otorgando el ejor serviso a nuestros clientes',
        'success'
        )
    })
  })
</script>

<script>
    $(document).ready(function(){
      $("#btnjs3").click(function(){
        Swal.fire(
        'Objetivos',
        'Cumplir con las necesidades del cliente, Que nuestros paquetes de hoteles y viajes sean los mejores, Realizar el mejor tiempo en atencio al cliente, Atender todas la cesidades de nuestros clientes',
        'success'
        )
    })
  })
</script>





<style>
  
    #contenedor_1{
        height: 500px ;
        width: 350px; 
        background-color: rgba(28, 51, 184, 0.815);
        padding-top: 200px;
        margin-left: 30px;
        color: white;
        font-family: Arial, Helvetica, sans-serif;
       

    }
    
    #contenedor_2{
        height: 500px ;
        width: 350px; 
        background-color: rgba(190, 65, 7, 0.699);
        padding-top: 200px;
        margin-left: 900px;
        color: white;
        text-align: center;
        font-family: Arial, Helvetica, sans-serif;
       

    }

    #contenedor_3{
        height: 500px ;
        width: 350px; 
        margin-left: 30px;
        background-color: rgba(185, 4, 4, 0.74);
        padding-top: 200px;
        color: white;
        font-family: Arial, Helvetica, sans-serif;
        

    }
    #contabout1{
      
        background-image:url("{% static 'img/hosp.jpg' %}");
        text-align: center;
		height: 500px;
		width: 1350px;
		background-repeat: no-repeat;
        background-attachment: fixed;
		background-position: center;
		background-size: cover;
		position: relative;
       
        
		
          
    }
    #contabout2{
        width: 1350px;
        height: 500px;
        background-image:url("{% static 'img/reset2.jpg' %}");
        background-repeat: no-repeat;
        background-attachment: fixed;
		background-position: center;
		background-size: cover;
		position: relative;
        
        
    }
    #contabout3{
        width: 1350px;
        height: 500px;
        background-image:url("{% static 'img/lugares.png' %}");
        background-repeat: no-repeat;
        background-attachment: fixed;
		background-position: center;
		background-size: cover;
		position: relative;
        text-align:center;
        
    }
    #up_tit{
        text-align: center;
        border-bottom-color:rgba(14, 13, 13, 0.219);
        border-bottom-style: solid;

    }
    
</style>

{% endblock content %}

pages/templates/CreateVuelo.html
<style>
   p{
        color: white;
    }
    #id_ciudad{
        width: 350px;
        height: 30px;
        margin-left: 35px;
    }
    #id_descrpicion{
        width: 350px;
        height: 30px;
        margin-left: 10px;
    }
    #id_escala{
        width: 350px;
        height: 30px;
        margin-left: 40px;
    }
    #id_presio{
        width: 350px;
        height: 30px;
        margin-left: 45px;
    }
    #id_img{
        width: 350px;
        height: 30px;
        margin-left: 50px;
    }
    #btn_guardar{
        color:green;
        width: 150px;
        height: 40px;
    }
    #tit{
        color: white;
        font-family: Arial, Helvetica, sans-serif;
        margin-bottom: 30px;
    }
    #conte_vuelo{
        text-align: center;
    }

</style>
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!--creacion de un nuevo vuelo -->
<div id="cont_super">
    <div id="cont_vu">
    <h1 id="tit"> Agregar Vuelo</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        {{form.media}}
        {{form.as_p}}
    <input type="submit" value="Guardar" id="btn_guardar"> 
    </form>
</div>
</div>

<style>
    #cont_vu{
        background-color: rgba(0, 0, 0, 0.473);
        width: 700px;
        margin-left: 300px;
        height: 450px;
    }
	
	#cont_super{
        padding-top: 50px;
        text-align: center;
		background-image:url("{% static 'img/reset.jpg' %}");
		height: 600px;
		width: 1200px;
		background-repeat: no-repeat;
		background-position: center;
		background-size: cover;
		position: relative;
		
		color: white;
	}

</style>

{% endblock content %}

pages/templates/DescViajes.html
{% extends 'base.html' %}
{% load static %}
<!--descripcion de un Hospedaje   -->
<ul id="lista_1">
    <h1> Descripcion del viaje</h1>
    
    {% block content %}
    
         <!--descripcion de un modelo de hospedaje   -->
<div id="cont_f">
    <div id="datos_div">
        <div><h2>Destino:{{Listado_viajes_des.ciudad}}</h2></div>
        <img id="img_div" src = {{Listado_viajes_des.img.url}} >
        <div>Destino:{{Listado_viajes_des.ciudad}}</div>
        <div>Detalles:{{Listado_viajes_des.descrpicion}}</div>
        <div>Numero de Noches:{{Listado_viajes_des.noches}}</div>
        <a type="button" class="btn" href="{% url 'orders_viaje' Listado_viajes_des.pk %}" id="btn_comprar"><strong>Pagar: ${{Listado_viajes_des.presio}}</strong></a>
         

        
    </div>


    <div id="coment">
        <div id="coment_1">
                <h2>Seccion de comentarios</h2>
            </div>
            <div id="coment_2">
            {% for comentario in Listado_viajes_des.comentariosViaje.all %}
            <div style="border-bottom: white;border-bottom-style: solid;">
                <span class="font-wigth-bold"><b>{{comentario.autor}}</b></span><br>
                <span class="font-wigth-bold">{{ comentario}}</span>
            </div>	
            {%endfor%}
            <br>
            <a type="button" class="btn btn-primary" href="{% url 'comentarioNuevoV' Listado_viajes_des.pk %}" id="btn_rojo_1"><strong>Comentar</strong></a>
				
           
        </div>	
    </div>

</div>

<style>
    #btn_rojo_1{
        margin-left: 35%;
        width: 200px;
        margin-bottom: 20px;
    }

     #coment{
        width: 45%;
        float: left;
        margin-left: 30px;
        margin-top: 100px;
        padding-top: 30px;
       

     }
     #datos_div{
        width: 45%;
        float: left;
        background-color: rgba(0, 0, 0, 0.548);
        margin-left: 30px;
        text-align: center;
        margin-top: 100px;
        padding-top: 30px;
        color: white;
     }

     #img_div{
         width: 300px;
         height: 250px;
     }

     #coment_1{
        background-color: rgba(9, 7, 133, 0.836);
        color: white;
        text-align: center;
        border-radius: 50px;
     }

     #coment_2{
         font-family: Arial, Helvetica, sans-serif;
         font-size: 16px;
         color: white;
         background-color: rgba(201, 56, 12, 0.829);

     }

     #cont_f{
        
        background-image:url("{% static 'img/hoteles_cancun_.jpg' %}");
        height: 600px;
        width: 1350px;
        background-repeat: repeat;
        background-position: auto;
        background-size: cover;
        background-attachment: fixed;
     }

     #btn_comprar{
    background-color: rgb(255, 255, 255);
    border-color: rgba(128, 128, 128, 0.226);
    color: indigo;
    border-radius:10px;
   
}

 
 </style>
    {% endblock content %}
</ul>  

pages/templates/EditarHospedaje.html
<style>
    p{
         color: white;
     }
     #id_ciudad{
         width: 350px;
         height: 30px;
         margin-left: 35px;
     }
     #id_beneficios{
         width: 350px;
         height: 30px;
         margin-left: 10px;
     }
     #id_escala{
         width: 350px;
         height: 30px;
         margin-left: 40px;
     }
     #id_presio{
         width: 350px;
         height: 30px;
         margin-left: 45px;
     }
     #id_img{
         width: 350px;
         height: 30px;
         margin-left: 50px;
     }
     #btn_guardar{
         color:green;
         width: 150px;
         height: 40px;
     }
     #tit{
         color: white;
         font-family: Arial, Helvetica, sans-serif;
         margin-bottom: 30px;
     }
     #conte_vuelo{
         text-align: center;
     }
 
 </style>
 {% extends 'base.html' %}
 {% load static %}
<!--valores para ediar del modelo de Hospedaje-->
{% block content %}

<div id="cont_super">
    <div id="cont_vu">
    <h1 id="tit">Editar Hospedaje</h1>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        {{form.media}}
        {{form.as_p}}
      <input type="submit" id="btnjs" value="Guardar" id="btn_guardar"> 
    </form>

</div>
   

</div>


<style>
	#cont_vu{
        background-color: rgba(0, 0, 0, 0.473);
        width: 700px;
        margin-left: 300px;
    }
    #cont_super{
        padding-top: 50px;
         text-align: center;
        background-image:url("{% static 'img/hosp2.jpg' %}");
        height: 600px;
        width: 1350px;
        background-repeat: repeat;
        background-position: auto;
        background-size: cover;
        background-attachment: fixed;
        color: white;
    }

</style>

{%endblock content %}

pages/templates/EditarViaje.html
<style>
    p{
         color: white;
     }
     #id_ciudad{
         width: 350px;
         height: 30px;
         margin-left: 35px;
     }
     #id_descrpicion{
         width: 350px;
         height: 30px;
         margin-left: 10px;
     }
     #id_noches{
         width: 350px;
         height: 30px;
         margin-left: 40px;
     }
     #id_presio{
         width: 350px;
         height: 30px;
         margin-left: 45px;
     }
     #id_img{
         width: 350px;
         height: 30px;
         margin-left: 50px;
     }
     #btn_guardar{
         color:green;
         width: 150px;
         height: 40px;
     }
     #tit{
         color: white;
         font-family: Arial, Helvetica, sans-serif;
         margin-bottom: 30px;
     }
     #conte_vuelo{
         text-align: center;
     }
 
 </style>
{% extends 'base.html' %}

{% load static %}
<!--valores para ediar del modelo de Viajes-->
{% block content %}

<div id="cont_super">
    <div id="cont_vu">
    <h1 id="tit">Editar Viajes</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}} 
    {{form.as_p}}
<input type="submit" value="Guardar" id="btn_guardar"> 
</form>
</div>
</div>
<style>
	#cont_vu{
        background-color: rgba(0, 0, 0, 0.473);
        width: 700px;
        margin-left: 300px;
    }
    #cont_super{
        padding-top: 50px;
         text-align: center;
        background-image:url("{% static 'img/reset2.jpg' %}");
        height: 600px;
        width: 1350px;
        background-repeat: repeat;
        background-position: auto;
        background-size: cover;
        background-attachment: fixed;
        color: white;
    }

</style>

{%endblock content %}

pages/templates/EditarVuelo.html
<style>
    p{
         color: white;
     }
     #id_ciudad{
         width: 350px;
         height: 30px;
         margin-left: 35px;
     }
     #id_descrpicion{
         width: 350px;
         height: 30px;
         margin-left: 10px;
     }
     #id_escala{
         width: 350px;
         height: 30px;
         margin-left: 40px;
     }
     #id_presio{
         width: 350px;
         height: 30px;
         margin-left: 45px;
     }
     #id_img{
         width: 350px;
         height: 30px;
         margin-left: 50px;
     }
     #btn_guardar{
         color:green;
         width: 150px;
         height: 40px;
     }
     #tit{
         color: white;
         font-family: Arial, Helvetica, sans-serif;
         margin-bottom: 30px;
     }
    
 
 </style>
{% extends 'base.html' %}
{% load static %}
<!--valores para ediar del modelo de Vuelo-->
{% block content %}

<div id="cont_super">
    <div id="cont_vu">
    <h1 id="tit">Editar Vuelos</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %} 
    {{form.media}}
    {{form.as_p}}
<input type="submit" value="Guardar" id="btn_guardar"> 
</form>
</div>
</div>

<style>
	#cont_vu{
        background-color: rgba(0, 0, 0, 0.473);
        width: 700px;
        margin-left: 300px;
    }
    #cont_super{
        padding-top: 50px;
         text-align: center;
        background-image:url("{% static 'img/reset.jpg' %}");
        height: 600px;
        width: 1350px;
        background-repeat: repeat;
        background-position: auto;
        background-size: cover;
        background-attachment: fixed;
        color: white;
    }

</style>
{%endblock content %}

pages/templates/comentarioNuevo.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div id="conte_vuelo">
    <div id="cont_vu">
        <h1> Comentarios</h1>
        <p>Agregar un comentario </p>
        <form action="" method="post">{% csrf_token %} 
            {{form.as_p}}
           
        <input type="submit" value="Guardar" class="btn btn-primary" id="btn_guardar"> 
        </form>
    </div>
</div>


<style>
    #btn_guardar{
        margin-top: -150px;
    }


    #id_Vuelo{
       opacity: 0;
       margin-left: 900px;
    }
    label{
        opacity: 0;
    }
    #cont_vu{
       background-color: rgba(0, 0, 0, 0.473);
       width: 700px;
       margin-left: 300px;
       height: 300px;
   }
   #id_comentario{
       padding-top: 20px;
       width: 400px;
       height: 100px;
       margin-left: -100px;
   }
   
   #conte_vuelo{
       padding-top: 50px;
        text-align: center;
       background-image:url("{% static 'img/hosp2.jpg' %}");
       height: 600px;
       width: 1350px;
       background-repeat: no-repeat;
       background-position: center;
       background-size: cover;
       position: relative;
       
       color: white;
   }

</style>

{%endblock content %}

pages/templates/comentarioNuevoV.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div id="conte_vuelo">
    <div id="cont_vu">
        <h1> Comentarios</h1>
        <p>Agregar un comentario </p>
        <form action="" method="post">{% csrf_token %} 
            {{form.as_p}}
           
        <input type="submit" value="Guardar" class="btn btn-primary" id="btn_guardar"> 
        </form>
    </div>
</div>


<style>
    #btn_guardar{
        margin-top: -150px;
    }

    #id_Viaje{
       opacity: 0;
       margin-left: 900px;
    }
    label{
        opacity: 0;
    }
    #cont_vu{
       background-color: rgba(0, 0, 0, 0.473);
       width: 700px;
       margin-left: 300px;
       height: 300px;
   }
   #id_comentario{
       padding-top: 20px;
       width: 400px;
       height: 100px;
       margin-left: -100px;
   }
   
   #conte_vuelo{
       padding-top: 50px;
        text-align: center;
       background-image:url("{% static 'img/hosp2.jpg' %}");
       height: 600px;
       width: 1350px;
       background-repeat: no-repeat;
       background-position: center;
       background-size: cover;
       position: relative;
       
       color: white;
   }

</style>

{%endblock content %}

pages/templates/createCiudad.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div id="conte_vuelo">
    <div id="cont_vu">
        <h1> Comentarios</h1>
        <p>Agregar una Ciudad </p>
        <form action="" method="post">{% csrf_token %} 
            {{form.as_p}}
           
        <input type="submit" value="Guardar" class="btn btn-primary" id="btn_guardar"> 
        </form>
    </div>
</div>


<style>
    #btn_guardar{
        margin-top: -10px;
    }


  
    label{
        opacity: 0;
    }
    #cont_vu{
       background-color: rgba(0, 0, 0, 0.473);
       width: 700px;
       margin-left: 300px;
       height: 300px;
   }
   #id_nombre{
       text-align: center;
       font-family: Arial, Helvetica, sans-serif;
       font-size: 15px;
       padding-top: 20px;
       width: 250px;
       height: 25px;
       margin-left: -100px;
   }
   
   #conte_vuelo{
       padding-top: 50px;
        text-align: center;
       background-image:url("{% static 'img/hosp2.jpg' %}");
       height: 600px;
       width: 1350px;
       background-repeat: no-repeat;
       background-position: center;
       background-size: cover;
       position: relative;
       
       color: white;
   }

</style>

{%endblock content %}

pages/templates/deleteVuelos.html
<style>
  #tit{
     color: white;
     font-family: Arial, Helvetica, sans-serif;
    
 }

 #btn_guardar{
     color:red;
     width: 150px;
     height: 40px;
     
 }
 #img_div{
     width: 300;
     height: 250px;
     margin-bottom: 30px;
 }
</style>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--Formulario para eliminar-->
<div id="cont_super">
<div id="cont_vu">
<h2 id="tit">Seguro que deseas eliminar el registro ?</h2>
<img id="img_div" src = {{Listado_viajes_des.img.url}} >

<h3 id="tit"> presio : ${{Listado_viajes_des.ciudad}}</h3>
<h3 id="tit"> presio : ${{Listado_viajes_des.presio}}</h3>
    <form action="" method="post">
            {% csrf_token %} 
            {{form.as_p}}
        <input type="submit" value="Confirmar" id="btn_guardar"> 
    </form>
</div>
</div>
<style>
#cont_vu{
    background-color: rgba(0, 0, 0, 0.473);
    width: 700px;
    height: 500px;
    margin-left: 300px;
}
#cont_super{
    padding-top: 50px;
     text-align: center;
    background-image:url("{% static 'img/reset.jpg' %}");
    height: 600px;
    width: 1350px;
    background-repeat: repeat;
    background-position: auto;
    background-size: cover;
    background-attachment: fixed;
    color: white;
}

</style>
{%endblock content %}

pages/templates/search_result_hosp.html
<style>
    #cont_v{
        border-color: rgb(107, 36, 95);
        border-style: solid;
        width: 30%;
        height: 400px;
        float: left;
        text-align: center;
        margin-left: 30px;
        margin-top: 25px;
        border-radius: 30px;
    }
    #home_img{
        width: 300px;
        height: 250px;
        border-radius: 20px;
    }
    #lista{
        list-style: none;
    }
</style>

{% extends 'base.html' %}

{% block title %} Busquedas{% endblock title %}
{% block content %}

{% for hosp in listaBook  %}

    <div id="cont_v">
        <h2><a  href="{% url 'DescHosp' hosp.pk %}">{{ hosp.ciudad }}</a></h2>
        <li id="lista">Descripcion:{{ hosp.descrpicion}}</li>
        <li id="lista">Escala:{{ hosp.escala}}</li>
        <li id="lista">Presio:{{hosp.presio}}</li>
        <img id="home_img" src = {{hosp.img.url}} >
    </div>
{% endfor %}
{% endblock content%}

pages/templates/search_result_viaje.html
<style>
    #cont_v{
        border-color: rgb(107, 36, 95);
        border-style: solid;
        width: 30%;
        height: 400px;
        float: left;
        text-align: center;
        margin-left: 30px;
        margin-top: 25px;
        border-radius: 30px;
    }
    #home_img{
        width: 300px;
        height: 250px;
        border-radius: 20px;
    }
    #lista{
        list-style: none;
    }
</style>

{% extends 'base.html' %}

{% block title %} Busquedas{% endblock title %}
{% block content %}

{% for hosp in listaBook  %}

    <div id="cont_v">
        <h2><a  href="{% url 'DescViajes' hosp.pk %}">{{ hosp.ciudad }}</a></h2>
        <li id="lista">Descripcion:{{ hosp.descrpicion}}</li>
        <li id="lista">Escala:{{ hosp.escala}}</li>
        <li id="lista">Presio:{{hosp.presio}}</li>
        <img id="home_img" src = {{hosp.img.url}} >
    </div>
{% endfor %}
{% endblock content%}